### ISSUE TITLE
Unable to save blog post with translate plugin

### ISSUE THREAD

**Issue by ghost** [jan-vince/smallextensions#1]
So I have both translate and blog installed with your editor. Your editor is really awesome and it really helps especially I cannot find anything similar that support both rainlab blog and translate.

Just one thing I notice, if I try to have a blog post with 2 language, it looks like only the default language's post can be save. With the additional language, I can still do editing to it, and I can still save it, but the changes did not appear on the website.

I was wondering if this is something related to your plugin, or to the other plugin?

**Comment by jan-vince** [comment]
Hi, I have checked this and it works for me. 

Maybe you don't switch languages correctly?

Try to dump current locale to see, that it is really switched.

In layout you can do it with PHP code like this:

```php
==
<?php

function onInit(){
    dump( App::getLocale() );
}

?>
==
```

*I am using default October richeditor, so all credits go to its authors :)*

**Comment by ghost** [comment]
I have tried to use that, and it does tells me I am really switched

This first screen shot is the changes I made at blog and after save
![screen shot 2017-04-28 at 9 05 54 am gmt 8](https://cloud.githubusercontent.com/assets/24636595/25510327/f602c158-2bf1-11e7-8154-1390021beafa.png)

This is what I see currently at my blog
![screen shot 2017-04-28 at 9 06 08 am gmt 8](https://cloud.githubusercontent.com/assets/24636595/25510328/f64389ae-2bf1-11e7-8c43-3ff2a2dce14f.png)

So I tried to disable your plugin and then perform a save for different language, then I can see the changes at my blog. Really not sure which part is the error part right here

**Comment by jan-vince** [comment]
Can you post here a content of a static page you created and saved?

It will be in /content/static-pages/

There we can look, how the content was saved.

**Comment by ghost** [comment]
I did not create any static-page for the blog post, I mainly use one of the partials for it, should I just use that?

{% set image = post.featured_images.first %}
<article>

    {% if image %}
        <div class="post-image">
            <a href="{{ post.url }}"><img src="{{ image.path }}" alt="{{ post.title }}" /></a>
        </div>
    {% else %}
        <header class="post-title">
            <h1><a href="{{ post.url }}">{{ post.title }}</a></h1>
        </header>
    {% endif %}

    <div class="post-content">
        {{ post.summary|raw }}
    </div>

    <footer>
        <span class="published"><i class="icon icon-calendar"></i> {{ post.published_at|date('M d, Y') }}</span>
        {# <span class="author"><i class="icon icon-user"></i> {{ post.author.full_name }}</span> #}
        {% if post.categories.count %} in
            <span class="category">
                <i class="icon icon-folder-open"></i>
                {% for category in post.categories %}
                    <a href="{{ category.url }}">{{ category.name }}</a>{% if not loop.last %}, {% endif %}
                {% endfor %}
            </span>
        {% endif %}
    </footer>
</article>

**Comment by ghost** [comment]
Anything else I need to provide to you? I have tried to trace back how rainlab blog put the post, but no success yet...

**Comment by jan-vince** [comment]
I have just tried to use CMS page and partial to render post and it worked for me.

First, please try to look inside of your database (if you know how to do it) and look for rainlab_translate_attributes table.

Inside of it, there are translated strings - blog posts will have ````RainLab\Blog\Models\Post```` in column ````model_type````.

Here you can check that your translated strings are saved.

If you see your translated strings here, problem will be in your code.


I have made [short video to overview my setup](http://www.youtube.com/watch?v=Vyxn8KxJTXA).

**Comment by ghost** [comment]
I had checked the table and I can see my translated strings.

So when you say is my code issue, does that mean related to the actual Rainlab Blog's code or potentially any custom code that I might have changed?

**Comment by jan-vince** [comment]
Most probably there is a problem in your page/partial code or configuration.

I would go this way:

* be sure, your locale is correctly changed ( ````dump( App::getLocale() )```` in PHP section )
* double check URLs in your CMS page (for all locales !)
* create empty testing CMS page only with Locale picker and Post components and try to visit this page with blog post slug added - then try to manually change locale in URL

*I can't help much more without seeing your code.*
