### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by AntonIlinykh** [jan-vince/smallextensions#10]
Hello and thank you for this very handy plugin!

But I can't see in the docs how do I make localization.
I need to add a new langauge, not just switch to cs (which is included).

I believe, the first step is to create lang.php with all appropriate strings.
What's next?

**Comment by jan-vince** [comment]
Hi @AntonIlinykh, what exactly do you need to localize?

**Comment by AntonIlinykh** [comment]
Almost everything gets translated with exception of these:
At least 2 labeles in the WYSIWYG editor (insert audio, insert file).
All 4 options for paragraph style.
And Featured Image section.

Although I'm not sure is it issue with Small Extensions, Blog plugin, or with October itself.

**Comment by jan-vince** [comment]
Hi @AntonIlinykh,

this is a problem with Richeditor component that is a core part of OctoberCMS. I cannot change it from within my plugin.

If you don't see some parts localized, you can help translate it by [creating PullRequest in lang](https://github.com/octobercms/october/tree/master/modules/backend/lang).
