### ISSUE TITLE
Translatable Relation

### ISSUE THREAD

**Issue by osmanzeki** [jan-vince/smallextensions#11]
https://github.com/jan-vince/smallextensions/blob/6f7d2c98ec42fe4b403f1a0fd69365a82915909b/Plugin.php#L279

I was able to get relations to translate using the Trait fix mentioned here. Could be a temporary fix for your problem :
https://github.com/rainlab/translate-plugin/issues/209#issuecomment-293534357

It seems like it only needs a Pull Request to be integrated into RainLab.Translate officially but I can confirm it works on my end of things with this solution for now.

Cheers!

**Comment by jan-vince** [comment]
Hi @osmanzeki, I will at this.

Thanks! :)

**Comment by LukeTowers** [comment]
Fixed by https://github.com/octobercms/october/commit/13d710b161bdf65a19f38f974c259bc4997a162c
