### ISSUE TITLE
Featured images on Categories

### ISSUE THREAD

**Issue by haralake** [jan-vince/smallextensions#14]
First of all this is a very good high quality plugin and i'm really thank you for that. I want to give you one idea to make it even better. Add Featured Images feature on Blog Categories. I thing is a very good feature to have.

Thank you again.

**Comment by jan-vince** [comment]
Hi @haralake, good point! I don!t have much time but add this to my todo list.

Best regards,

Jan

**Comment by haralake** [comment]
Thank you Jan Vince! This plugin is a must have if you want to customize blog plugin, adding classes to posts e.t.c . The only thing i notice is the lack of categories support and the best would be the featured images addition.
Thanks again for your interest and for this excellent plugin!!

**Comment by jan-vince** [comment]
Hi @haralake and thanks, I will add this to my todo list :)
