### ISSUE TITLE
Keeping line breaks and paragraphs when switching to WYSIWYG editor

### ISSUE THREAD

**Issue by gavinworks** [jan-vince/smallextensions#15]
Firstly, AMAZING plugin. I only wish I had seen this sooner! When switching on the WYSIWYG editor after using the default markdown editor the linebreaks and paragraphs aren't preserved. The editor instead adds all markdown paragraphs into just **one** `<p></p>` tag. I have hundreds of blog posts.

Is there a way to preserve markdown paragraphs and translate them into paragraphs when switching on the WYSIWYG editor?

Many thanks
Gavin

**Comment by jan-vince** [comment]
Hi @gavinworks, the only way would be to write a script (or October plugin) that goes through all your Blog posts in database and transform them from MD to HTML.

I have never needed this so I probably will not add this feature.

Sorry for the late answer!
