### ISSUE TITLE
How to add custom fields to Rainlab.Blog?

### ISSUE THREAD

**Issue by mvk843** [jan-vince/smallextensions#18]
Hello! I've installed small extensions, but cannot find how to add custom fields to blog posts. Please help.

**Comment by mvk843** [comment]
I found, in Options - Small Extensions - Blog. But just one field of one type. What if I want to add 2 or more textareas?

**Comment by jan-vince** [comment]
Hi @mvk843,

you can use `Add REPEATER` option where you can define some fields and in Blog post you will have option to add more records to repeater.

Sorry for the late answer.
