### ISSUE TITLE
Images from Media are sorted randomly when selecting.

### ISSUE THREAD

**Issue by Lajmenko** [jan-vince/smallextensions#19]
Hello, 

I am uploading decent-sized batches of photos in posts, and I have noticed that using media picker to put group of images (either by shift-clicking them, or by drag-selecting multiple items at once) puts them into the content of post, in completly random order.

I have run tests about it, and even selecting same batch of images again and again will always post them in a different order than the before - aka. completly random order of insertion. 

Is it possible to make images appear in post contest with order they have been selected/filename/any metadata?

**Comment by jan-vince** [comment]
Hi @Lajmenko, this is probably not related to my plugin - if I understand right, you are working with images inside of a Blog post.

Let me know if I am missing something.

And sorry for late answer.
