### ISSUE TITLE
Snippets support for rainlab blog with janvince.smallextensions

### ISSUE THREAD

**Issue by xkapr** [jan-vince/smallextensions#20]
Hi, i have Rainlab.Blog and janvince.smallextensions installed. I want to use richeditor snippets extension in blog editing. The snippets menu appears in richeditor menu while blog post editing. It also inserts the snippet. But the snippet is broken when save and reopen. And does not appear on live site.
It is possibility to implement this functionallity?

**Comment by jan-vince** [comment]
Hi @xkapr, as far as I know, Snippets are only supported by Static Pages plugin.

It's not supported by Blog plugin.

Sorry for late answer.
