### ISSUE TITLE
How to add a column to filter blogs in the backend?

### ISSUE THREAD

**Issue by exaline-ru** [jan-vince/smallextensions#21]
How to add a column to filter blogs in the backend?
(plugins/rainlab/blog/models/post/columns.yaml)

**Comment by jan-vince** [comment]
Hi @exaline-ru, can you post some screenshots of what you mean?

**Comment by exaline-ru** [comment]
In rainlab blog I use some fields from your plugin:

![image](https://user-images.githubusercontent.com/46493161/69412222-808b9500-0d1f-11ea-914d-15571f3ed3c9.png)

And in the list of blogs I want to add a column for these fields:

![image](https://user-images.githubusercontent.com/46493161/69412405-d8c29700-0d1f-11ea-8211-05d2d3376fc8.png)

**Comment by jan-vince** [comment]
Hi @exaline-ru this is not implemented in my plugin.

But you can create pull request and I will add it or create your own plugin to extend Rainlab Blog.
