### ISSUE TITLE
Add Custom fields REPEATER {{post.custom_fields.repeater}} Error.

### ISSUE THREAD

**Issue by alanhwi** [jan-vince/smallextensions#22]
Hi!

Following the plugin's instructions, I added Custom fields REPEATER, Twig: {{post.custom_fields.repeater}}, but there was an error on the front-end page,

Front-end warning content:

"An exception has been thrown during the rendering of a template (" Array to string conversion ")."

My steps are like this:

1. Check "Add REPEATER" and add Field label: website

2. Select "Show Title" and add Field label: showtitle

3. Check "Show Description" and add Field label: showdescription

Then I went to my blogCategories page and referenced partial, and added {{post.custom_fields.repeater}} in partial. Then the above error appeared. May I need other code? I read the description of the plugin, No answer found, how can I do to display the field content of the repeater on the front page? Thank you!

Note: I also tested Twig: {{post.custom_fields.string}}, this field can be displayed well on the front page.

**Comment by jan-vince** [comment]
Hi @alanhwi,
`{{post.custom_fields.repeater}}` will return array with repeater fields - but Twig cannot directly display arrays.

You will have to iterate through the fields like:

```
{% for field in post.custom_fields.repeater %}
   {{ field.someFieldName }} {# use name of your field in repeater #}
{% endfor %}
