### ISSUE TITLE
Add more fonts

### ISSUE THREAD

**Issue by akiuni** [jan-vince/smallextensions#24]
Hello

Would it be possible to improve your plugin by adding more fonts in the Richeditor ? Or tell us in the documentation a reliable way to import new fonts in your plugin ?

By defaults, I've got "Arial, Georgia, Impact, Tahoma, Time new Roman and Verdana". I've tried some solutions ( like this one : https://github.com/octobercms/october/issues/3679), but either they are not working, or they are causing bad border effects. 
I hope that you may have a nice reliable solution for your plugin ?

Thank you
best regards
Julien

**Comment by jan-vince** [comment]
Hi @akiuni,

I am using October's default WYSIWYG editor so you will have to [send issue there](https://github.com/octobercms/october/issues).

*PS: You can add CSS classes to WYSIWYG editor and style your content as you like.*



Best regards,

Jan

**Comment by akiuni** [comment]
Hello @jan-vince Jan
Thank you for your answer, fyi I've done it here : https://octobercms.com/forum/post/how-to-add-more-fonts-to-froala-richeditor

And congratulations for you plugin, it is nice and working very well !
Best regards
Julien
