### ISSUE TITLE
Post preview image (from upload) to download multiple images

### ISSUE THREAD

**Issue by SciCrea** [jan-vince/smallextensions#25]
Hi, how can I use the "Post preview image (from upload)" to download not a single image (attachOne) but a set (attachMany)? I want to use it as a gallery.

**Comment by jan-vince** [comment]
Hi @SciCrea

this is meant to be a single image. You can use original `Featured images` to upload several images.

**Comment by SciCrea** [comment]
> 
> 
> Hi @SciCrea
> 
> this is meant to be a single image. You can use original `Featured images` to upload several images.

Thank you, I'll do it!
