### ISSUE TITLE
Not possible to install it in Winter CMS

### ISSUE THREAD

**Issue by qroft** [jan-vince/smallextensions#26]
Greetings Jan! I tried to install the plugin with Winter CMS, but obviously it can not find the Rainlab DB tables as they have been renamed for the Winter CMS project.

As i do not consider myself a developer i do have some questions.
1. Are you planning to updated the Plugin, so that when a Winter CMS user tries the installation there could be a simple "IF rainlab.blog.table exists, good, otherwise take winter.blog.table ?
2. Can i make a commit somehow here inside? I am definitly no GIT expert so i am afraid of "breaking" anything. LOL

Wish you the best and thanks for this plugin!

**Comment by jan-vince** [comment]
Hi,

i am sorry, but I do not plan to support WinterCMS.

The best way is to fork my plugin and make changes you need.



Best regards,

Jan


< Ing. Jan Vince / webdesigner / +420 733 127 581 / www.vince.cz />
