### ISSUE TITLE
Post.featured_images not working when using the Media Manager

### ISSUE THREAD

**Issue by kevinvermeulenn** [jan-vince/smallextensions#7]
I've used the option to add my featured image via the Media Manager. 
Before the change I use this code: 
`{% for image in post.featured_images|slice(0, 1) %}`
`<img class="img-responsive" src="{{ image.thumb(300,225,{mode:'crop',extension:'auto'}) }}" alt="{{ image.description != null ? image.description : image.filename }}" title="{{ image.title != null ? image.title : post.title }}">`
`{% endfor %}`

Since the change, it's not working anymore.  

How can I solve this?

**Comment by jan-vince** [comment]
Sure - as Media finder only serve URL, you can render your image like this:

````<img src="{{ post.custom_fields.featured_image|media }}">````

**Comment by kevinvermeulenn** [comment]
Thanks!

**Comment by kevinvermeulenn** [comment]
Is it also possible to get the title from the image @jan-vince ?

**Comment by jan-vince** [comment]
No way from image itself - Media Finder doesn't have this feature :(

But it's a good idea anyway.

I can add a text field below/above an image finder so you can enter an image title.

But when you use the same image in a different post, you will have to add the title again.

Does this make sense to have such a field even when you have to write a title by hand?

**Comment by kevinvermeulenn** [comment]
@jan-vince That will be a great and helpfull feature. For me it is no problem to add manual the title each time. Maybe it's also nice to have a description as well. 

So, I can use the title for the title="title" and description for alt="description"

**Comment by jan-vince** [comment]
Ok, it's done :)

In version 1.3.0 there is a new checkbox in Settings (next to Featured image) to allow title & description.

Twig codes are:

* Title:{{post.custom_fields.featured_image_title|media}}
* Description: {{post.custom_fields.featured_image_alt|media}}.


Thanks for suggestion!

*I will be glad if you can test it and let me know if there are any problems.*

**Comment by qroft** [comment]
Hi Jan-Vince, i think that the twig tags you mention in here should also be written inside the description of the plugin. As i am playing around with OctoberCMS i had three (!) plugins installed that offered a featured image exchange. This way i was unable to know what tag to use.
So i turned all off, apart of yours and finally i found this GitHub entry to know how to get the image.
Thanks a lot for the nice plugin!

**Comment by jan-vince** [comment]
Hi @qroft , in Settings description all those Twig tags are written.

But they are not in README - so I will add them there too.

Thanks!

![snimek obrazovky 2017-11-13 v 8 16 11](https://user-images.githubusercontent.com/1104383/32713795-23441888-c84b-11e7-9b82-a4b63333091c.png)

**Comment by kevinvermeulenn** [comment]
@jan-vince 
Currently, it doesn't work for me.
I used this code: 
```
<img src="{{post.custom_fields.featured_image|media|resize(1170, 620, { mode: 'crop'}) }}" width="1170" height="620" alt=" {{ post.custom_fields.featured_image_title|media }}">  
<figcaption>{{ post.custom.fields.featured_image_alt|media }}</figcaption>
```

**Output** 
Title:  /storage/app/media/This is a title
Description: /storage/app/media/

So, I missing the description itself and it should remove "/storage/app/media/".

**Comment by jan-vince** [comment]
Sure, there should be:
````{{ post.custom.fields.featured_image_title }}````
````{{ post.custom.fields.featured_image_alt }}````

In both cases ````|media```` should not be present.

I will fix this right away.

Thank you!

Jan
