### ISSUE TITLE
Error removing plugin

### ISSUE THREAD

**Issue by richardwo** [jan-vince/smallextensions#9]
Hi,
When I try to remove the plugin I get the following message:
`SQLSTATE[HY000]: General error: 1 no such column: featured_image_title (SQL
  : CREATE TEMPORARY TABLE __temp__janvince_smallextensions_blogfields AS SELECT id, post_id, api_code, string, text, switch, datetime, repeater, created_at, updated_at, image, featured_image, featured_image_title FROM janvince_smallextensions_blogfields)`

I'm running build 428 and using an sqlite database.

**Comment by jan-vince** [comment]
Hi, I have a same error but the query is OK when started from SQL editor so there will be somu bug in core maybe.

I will look at it as soon as I will have some time.

If you need to remove plugin now, just delete it's folder in ````/plugins/janvince/smallextensions```` and remove ````janvince_smallextensions_blogfields```` table from DB (but it is not necessary if you do not plan to install it again).

Thank you for the issue!

Best regards,

Jan

**Comment by jan-vince** [comment]
Hi @richardwo, finally fixed :)

Thanks!
